### ISSUE TITLE
Suggestion to add TailwindCSS for the UI

### ISSUE THREAD

**Issue by AKSHATH99** [LakshmiSowmya04/Task-Manager#21]
I am suggesting to use tailwindCSS for the UI of the project for much simple and easy designing . Since we haven’t started the UI yet, Tailwind CSS can make building the design faster and easier without writing custom CSS.I assume responsive designing would also be easy using tailwind .

**Comment by piyusss11** [comment]
yes i agree

**Comment by piyusss11** [comment]
okay sure

**Comment by AKSHATH99** [comment]
Alright . Thanks
