### ISSUE TITLE
Add css to the projects 

### ISSUE THREAD

**Issue by LakshmiSowmya04** [LakshmiSowmya04/Task-Manager#3]
This is just main part of this project I want UI od projects to look more better

**Comment by Sauhard74** [comment]
hi can i work on this issue?

**Comment by piyusss11** [comment]
@LakshmiSowmya04 if it's not taken can I work on this one?

**Comment by piyusss11** [comment]
> > @LakshmiSowmya04 if it's not taken can I work on this one?
> 
> You can make any changes to present exsisting one and share screen shot

okay in it

**Comment by piyusss11** [comment]
this was before 
![Screenshot (87)](https://github.com/user-attachments/assets/d32728c2-4282-422b-ae90-9f06ef848376)
![Screenshot (86)](https://github.com/user-attachments/assets/6755153a-2a84-4917-8456-5cfbfb9fcb61)
after styling , also added go back to dashboard so the user could go back through a click and not by changing the URL 
![Screenshot (92)](https://github.com/user-attachments/assets/ff1fe9c6-62a1-4fbc-aac9-1efb1150fe14)
![Screenshot (91)](https://github.com/user-attachments/assets/5f09e6b5-7f76-47d0-b910-0fa4071d1191)

if you approve ill make a PR
