### ISSUE TITLE
[Bug]: Integrate front end and backend and Make data pass to backend 

### ISSUE THREAD

**Issue by LakshmiSowmya04** [LakshmiSowmya04/Task-Manager#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unable to pass the data or retrive the data from backend

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vishal-kumar3** [comment]
hey @LakshmiSowmya04, is the frontend design completed? if frontend design is completed then i can integrate the backend and frontend. assign this issue to me under hacktoberfest.

**Comment by vishal-kumar3** [comment]
okay then i will make postman documentation for this. Assign me this issue

**Comment by Kp779** [comment]
hey, @LakshmiSowmya04 . I have looked into the issue. Doesn't seem to be a big deal to fix it. Please assign the task under hacktoberfest so that I can proceed with the problem solving of the task.

**Comment by vishal-kumar3** [comment]
Hey @LakshmiSowmya04, created an PR request for this.
