### ISSUE TITLE
Integrate CSS framework for project

### ISSUE THREAD

**Issue by Kp779** [LakshmiSowmya04/Task-Manager#38]
Integrate **TAILWIND**, a CSS framework into the project to enhance the development process by utilizing pre-built styles and components, thereby improving the UI consistency, responsiveness, and overall design quality across the application. This integration will streamline our styling workflow and allow developers to focus more on functionality rather than manually crafting basic UI elements.

WIth this issue being solved, we will also be addressing Issue #1, which aims to improve the user interface and ensure that the design is both responsive and visually appealing across different devices. This integration will directly support that goal by providing a solid foundation for responsive and consistent design elements. 

I have ideas for issue #1 which I have shared. Would love to finish this one and move ahead with issue #1 . If it suits you please assign me the issue under hactoberfest.

**Comment by AKSHATH99** [comment]
Tailwind has been initialised already . I think you can work on the UI imporvements

**Comment by Kp779** [comment]
@AKSHATH99 is right. Must have been added later on. @LakshmiSowmya04 you can unassign me and close the issue. Thank you

**Comment by AKSHATH99** [comment]
@LakshmiSowmya04  .,you meant to  remove the UI changes i made ?

**Comment by AKSHATH99** [comment]
> > @LakshmiSowmya04 .,you meant to remove the UI changes i made ?
> 
> no I mean....previously it was having design right...if you are not aware please go through the issues and see....I want you to make the design look like that and raise a PR ASAP using tailwind like you wished..is it clear?

Got it . You mean as per the design  mentioned in the issue #1  , right?
