### ISSUE TITLE
[Bug]: Issue with React-toastify import 

### ISSUE THREAD

**Issue by AKSHATH99** [LakshmiSowmya04/Task-Manager#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There seem to be issue in react-toastify import in the taskform and projectform files . It seem to throw module not found error . 

### Add ScreenShots

[
![Screenshot 2024-10-01 175448](https://github.com/user-attachments/assets/6a20cc08-b526-4501-866e-52292dba80a7)
](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by AKSHATH99** [comment]
I guess so . i think the package.json is not updated with that module

**Comment by Pulkitxm** [comment]
is this issue resolved? If not, can I work on this? @LakshmiSowmya04
