### ISSUE TITLE
[Feature Request]: Improve Naming Conventions for Consistency in Project Files

### ISSUE THREAD

**Issue by Pulkitxm** [LakshmiSowmya04/Task-Manager#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Some files in the project have inconsistent naming conventions. For example, files like `project.models.js` in `Task-Management-Backend/models` and `healthcheck-controllers.js` in `Task-Management-Backend/controllers` do not follow a clear or uniform naming style. This can lead to confusion and make it harder for developers to navigate the codebase.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Pulkitxm** [comment]
@LakshmiSowmya04  I would like to work on this issue under hacktoberfest

**Comment by Sahil-Gupta584** [comment]
@Pulkitxm also change the name of folder to just clien, server instead of gradlin-ui,gradlink-backend.not much but its bit uncomfortable to cd(moveto folder) to move and start serevr repeatedly

**Comment by Pulkitxm** [comment]
Done✅

**Comment by Sahil-Gupta584** [comment]
> no the reason we have named like this is it should be very clear to everyone that this is only frontend ...some people might feel confused with client and server...if they have many client folders it might be issue when opening in vscode...u can do shift+ctrl+c and shift+ctrl+v for copy paste in terminal when doing cd

i just suggested to make folder names a bit short if client,server can confuse then its of what about fronend,backend it more clear them>
