### ISSUE TITLE
[Bug]: whenever i try to add a new task it just throws some errors

### ISSUE THREAD

**Issue by Prathamesh0901** [LakshmiSowmya04/Task-Manager#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

this error occured when i tried to add a new task

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5fa43c87-fe88-4b02-b3be-d544458537bc)
![image](https://github.com/user-attachments/assets/fda02b30-3fe6-4529-a38e-b15860510a6b)
![image](https://github.com/user-attachments/assets/53ad0e04-d80a-451a-9cd6-43fd0692973c)
I would love to fix this!

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue
- [x] I'm willing to provide further clarification or assistance if needed.

**Comment by parvsehgal** [comment]
Hello i would love to contribute on this project can i please be assigned this issue i think i know why this error is happening this is probably due to there being no user creation frontend so a jwt token cannot be generated and the backend is throwing during authentication

**Comment by parvsehgal** [comment]
sure @Prathamesh0901 can i work on the frontend if thats fine with you ?

**Comment by Prathamesh0901** [comment]
actually i have made some changes in the frontend and made a pr. still there are issues regarding adding them in the backend. if you can help with that let me know.

**Comment by parvsehgal** [comment]
yeah i can tell what needs to be done in the BE ill mke pr

**Comment by Prathamesh0901** [comment]
in the backend are we using jwt authentication ? 
if yes, then how are we letting the user signup/signin ?
there is no signin/login page in the frontend

**Comment by Prathamesh0901** [comment]
so what should i do next ?
is someone working on for authentication on frontend and backend both ?

**Comment by parvsehgal** [comment]
Hello i have created a PR with user creation UI please look at it 🙏
