### ISSUE TITLE
[Feature Request]: Add User  Login  and Signup pages  in frontend 

### ISSUE THREAD

**Issue by AKSHATH99** [LakshmiSowmya04/Task-Manager#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to work on creating login and signup pages for the user . 

Please add this issue and its associated PR under Hacktoberfest . 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by parvsehgal** [comment]
Hello i have created a PR for this issue please take a look at it

**Comment by AKSHATH99** [comment]
Cool . I could work on redesigning it and adding routes and stuffs

**Comment by HarzhMehta** [comment]
Hey @AKSHATH99 ...... could you let me know whats the status ?

**Comment by AKSHATH99** [comment]
Hey.  I haven't started working on it yet . Will let you know by night

**Comment by AKSHATH99** [comment]
Hey @parvsehgal  , are you working on anything in this codebase right now ?

**Comment by parvsehgal** [comment]
No I am not currently working on this codebase
