### ISSUE TITLE
[Bug]: Unable to add new task.

### ISSUE THREAD

**Issue by Prathamesh0901** [LakshmiSowmya04/Task-Manager#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I created a new account and logged in. After that when i created a new project and tried to add a task to it, it couldn't.
![image](https://github.com/user-attachments/assets/0461f8f6-0b00-4f47-84a9-ec10e00131a0)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

Open to work on this issue.

**Comment by parvsehgal** [comment]
pls assign me this issue

**Comment by parvsehgal** [comment]
hello i was not able to reproduce the issue , so i made a controller that gets all the users tasks and shows them in the ui

**Comment by LakshmiSowmya04** [comment]
this is solved...please look into discord for further issues
