### ISSUE TITLE
[Feature Request]:  Layout and Password changes

### ISSUE THREAD

**Issue by manish-bhukar** [LakshmiSowmya04/Task-Manager#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the provided code we can login by putting a very weak password also instead of that we can add regex functionalities, and i also want to do change in layout ,because at time of sign up it not showing sign up name correct;y , that is got hiding below navbar
![Screenshot 2024-10-05 112104](https://github.com/user-attachments/assets/420c1ce8-3b66-4871-85df-cab5951423e0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by LakshmiSowmya04** [comment]
this is already solved please look into discord for more issues
