### ISSUE TITLE
[Feature Request]: Create a Dashboard UI 

### ISSUE THREAD

**Issue by saurabhpund** [LakshmiSowmya04/Task-Manager#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/ce0d43ec-efbc-4468-89b5-a0d76d70c264)
Suggested above UI to be implemented for the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by estevg** [comment]
Hi @LakshmiSowmya04 I would like to work on this issue. can I help?

**Comment by LakshmiSowmya04** [comment]
@estevg @Gourang12332 please communicate with saurabh and proceed
