### ISSUE TITLE
[Feature Request]: Implement Login UI 

### ISSUE THREAD

**Issue by saurabhpund** [LakshmiSowmya04/Task-Manager#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/a00bd389-4adb-4c0d-8b82-53d1898a2d82)
Implement suggested login UI

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by estevg** [comment]
Hi @LakshmiSowmya04 @saurabhpund I would like to work on this issue. can I help?

**Comment by LakshmiSowmya04** [comment]
> Hi @LakshmiSowmya04 @saurabhpund I would like to work on this issue. can I help? 

There are other issues mentioned in the discord ....please look into them
